server:
  port: 8004
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: http://192.168.138.100:3000/test/tensquare_config.git
          username: test
          password: test
  rabbitmq:
    host: 192.168.138.100
    username: test
    password: test
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
